# Generated by Django 4.1 on 2022-08-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myclubuser',
            old_name='fisr_name',
            new_name='fist_name',
        ),
    ]
