# Generated by Django 4.1 on 2022-08-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_fisr_name_myclubuser_fist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myclubuser',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
